### ISSUE TITLE
web3.js -> ethers.js

### ISSUE THREAD

**Issue by microchipgnu** [openverse/webxr-showcase#18]
Move web3.js to ethers.js. 

Some of the reasoning here: https://blog.infura.io/ethereum-javascript-libraries-web3-js-vs-ethers-js-part-i/

**Comment by barrasso** [comment]
Closed by #24

**Comment by microchipgnu** [comment]
Actually it is still WIP due to other web3 call we do on wallet.js

**Comment by barrasso** [comment]
Whoops good call
